org.gradle.caching=true
group=org.ballerinalang.azure_cosmosdb
version=4.2.0
ballerinaLangVersion=2201.8.0

checkstylePluginVersion=10.12.1
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=9.6.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0
jacocoVersion=0.8.14

# Azure CosmosDB dependencies
azureCosmosVersion=4.52.0
nettyVersion=4.1.100.Final
reactorNettyVersion=1.1.13
micrometerVersion=1.12.0
