org.gradle.caching=true
group=org.ballerinalang.azure_cosmosdb
version=4.3.0
ballerinaLangVersion=2201.8.0

checkstylePluginVersion=10.12.1
spotbugsPluginVersion=5.0.14
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0
ballerinaGradlePluginVersion=2.2.6

# Azure CosmosDB dependencies
azureCosmosVersion=4.83.0
nettyVersion=4.1.137.Final
reactorNettyVersion=1.2.18
micrometerVersion=1.15.12
azureCoreVersion=1.59.1
azureJsonVersion=1.5.1
azureXmlVersion=1.2.1
reactorCoreVersion=3.7.19
reactiveStreamsVersion=1.0.4
jacksonVersion=2.18.11
dropwizardMetricsVersion=4.1.0
latencyUtilsVersion=2.0.3
