name: Daily Build without Tests

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Daily Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/daily-build-connector-template.yml@main
    secrets: inherit
    with:
      repo-name: module-ballerinax-azure-cosmosdb
      additional-test-flags: "-x test"
