name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        required: true

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
          BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              env:
                  packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                  packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                  ./gradlew build
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      pack ./cosmosdb
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            
            - name: Push to Staging
              if: github.event.inputs.bal_central_environment == 'STAGE'
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      push 
              env:
                  WORKING_DIR: ./cosmosdb
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
                  JAVA_HOME: /usr/lib/jvm/default-jvm
             
             - name: Push to Dev
               if: github.event.inputs.bal_central_environment == 'DEV'
               uses: ballerina-platform/ballerina-action@2201.0.0
               with:
                  args:
                      push 
               env:
                  WORKING_DIR: ./cosmosdb
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
                  JAVA_HOME: /usr/lib/jvm/default-jvm
