name: Weekly Build

on:
  schedule:
    - cron: "15 2 * * 1"
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Weekly Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/daily-build-connector-template.yml@main
    secrets: inherit
    with:
      repo-name: module-ballerinax-azure-cosmosdb
